[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "docspec_python"
dynamic = ["version"]

[tool.uv.sources]
docspec = { workspace = true }
docspec-python = { workspace = true }

[tool.uv.workspace]
members = ["docspec/", "docspec-python/", "docs"]
exclude = ["docs"]
